jwt:
  header:Authorization
  secret:mySecret
  expiration:604800
  md5-key:randomKey

rest:
  auth-open: true #如果为true,则开启JWT的验证

mybatis-plus:
  mapper-locations: classpath*:com/binsoft/film/**/xml/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  type-handlers-package: com.binsoft.film.common.typehandler
spring:
  datasource:
    url: jdbc:mysql://192.168.1.7/film?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    druid:
      filters: log4j,wall,mergeStat


logging:
  level.root: info
  level.com.binsoft.film: debug
server:
  port: 8080

film:
  img-pre:http://img.binfilm.cn/



